# Generated by Django 5.1.6 on 2025-03-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_description_story_des_alter_story_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='des',
        ),
        migrations.AddField(
            model_name='story',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
