# Generated by Django 5.1.6 on 2025-03-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_story_des_story_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='summary',
            new_name='des',
        ),
    ]
