# Generated by Django 5.1.6 on 2025-03-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_summary_story_des'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-published_at',)},
        ),
        migrations.RenameField(
            model_name='story',
            old_name='des',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='publish',
            new_name='published_at',
        ),
    ]
